name: MLOps CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-train:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # Checkout repository
      # -------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------------
      # Set up Python
      # -------------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # -------------------------------
      # Install dependencies
      # -------------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 pytest-html

      # -------------------------------
      # Linting
      # -------------------------------
      - name: Run linting (flake8)
        run: |
          flake8 train tests --max-line-length=100

      # -------------------------------
      # Unit tests + HTML report
      # -------------------------------
      - name: Run unit tests
        run: |
          mkdir -p reports
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests/ \
            --html=reports/pytest_report.html \
            --self-contained-html

      # -------------------------------
      # Upload test report artifact
      # -------------------------------
      - name: Upload Pytest HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/pytest_report.html

      # -------------------------------
      # Model training (final model)
      # -------------------------------
      - name: Train final model
        run: |
          export PYTHONPATH=$(pwd)
          python -m train.train_experiment

      - name: Build Docker image
        run: |
          docker build -t heart-disease-api .

      - name: Run Docker container (smoke test)
        run: |
          docker run -d -p 8000:8000 heart-disease-api
          sleep 5
          curl -X POST http://localhost:8000/predict \
            -H "Content-Type: application/json" \
            -d '{"features":[63,1,145,233,1,0,150,0,2.3,0,0,1,0,0,1,0,0,1]}'
